### PR TITLE
fix failing workflow feat: Add Automated Deployment

### PR DESCRIPTION
**Pull request by mihrab34**
fix the failing workflow in PR  #35 

@manancodes - the Git configuration is now specific to the repository where the workflow runs

### CODE REVIEW

**Comment by manancodes** [comment]
Thanks @mihrab34 for the quick updates. 
I have one question though. Normally, I use the `deploy` script to build and deploy the project , and as far as I remember, I don't use push to the `gh-pages` manually. Why are we doing it here? I'm not very familiar with this part and need help from you.

**Comment by mihrab34** [comment]
@manancodes The reason for manually pushing to the `gh-pages` branch in the workflow is to control and customize the deployment process. It ensures that the deployment occurs exactly when and how you want it to, typically after a successful build

**Comment by manancodes** [comment]
> @manancodes The reason for manually pushing to the `gh-pages` branch in the workflow is to control and customize the deployment process. It ensures that the deployment occurs exactly when and how you want it to, typically after a successful build

I'm not very familiar with this. Are you certain this will work?

**Comment by manancodes** [comment]
@mihrab34

**Comment by mihrab34** [comment]
> @mihrab34

It will work. but i can also include a deploy script since you're more familiar with that.

**Comment by manancodes** [comment]
That would be awesome if you can do that. And create a separate PR for that.

**Comment by mihrab34** [comment]
okay

**Pull request closed without merging**
