### PR TITLE
Add deploy script to github workflow

### LINKED ISSUE #24: Automated Deployment
Create an automated workflow so that the Master branch gets uploaded to gh-pages automatically whenever new changes are made.

### PR DESCRIPTION
**Pull request by mihrab34**
# Pull Request Template

## Fixes Issue

**Closes #24**

## Proposed Changes

modified the github action deploy to gh-pages to run automatically when a push or PR is made to the master branch

## Checklist

Please check all the applicable boxes. To mark a box as done, use the following conventions:

```
- [x] - Correct; marked as done
- [ ] - Not correct; marked as **not** done
```

- [x] My code follows the code style of this project.
- [x] My commit messages are clear and concise
- [x] The title and description of the PR are clear and explain the approach.
- [x] I have performed a self-review of the code.
- [x] I have added proper comments wherever needed.
- [x] I have run my code through prettier to ensure consistency.

## Screenshots
testdeploy

## Related Issues

PR #37

### CODE REVIEW

**Comment by manancodes** [comment]
I'm still confused. 
Can you look into this once? https://github.com/gitname/react-gh-pages
As it says :
>  Then, the `deploy` script will push the contents of that folder to a new commit on the gh-pages branch of the GitHub repository, creating that branch if it doesn't already exist.

These are the steps I usually follow for deployment.

**Comment by mihrab34** [comment]
> I'm still confused. Can you look into this once? https://github.com/gitname/react-gh-pages As it says :
> 
> > Then, the `deploy` script will push the contents of that folder to a new commit on the gh-pages branch of the GitHub repository, creating that branch if it doesn't already exist.
> 
> These are the steps I usually follow for deployment.

Sure, I'll look into that. To explain the workflow, whenever new code changes is pushed or merged to the master branch, it automatically pushes the changes to the gh-pages branch after a successful build. I did the whole process in the script instead of using a package

**Comment by manancodes** [comment]
> > I'm still confused. Can you look into this once? https://github.com/gitname/react-gh-pages As it says :
> > > Then, the `deploy` script will push the contents of that folder to a new commit on the gh-pages branch of the GitHub repository, creating that branch if it doesn't already exist.
> > 
> > 
> > These are the steps I usually follow for deployment.
> 
> Sure, I'll look into that. To explain the workflow, whenever new code changes is pushed or merged to the master branch, it automatically pushes the changes to the gh-pages branch after a successful build. I did the whole process in the script instead of using a package

Why are we pushing to `gh-pages` manually in this case? Can't we do it using the deploy script?

**Comment by mihrab34** [comment]
@manancodes i'm using the package from https://github.com/gitname/react-gh-pages for the github action. You can check [here ](https://github.com/tschaub/gh-pages#deploying-with-github-actions-and-a-named-script)for further details on the package

**Review by manancodes — APPROVED** [review]

**Review by manancodes — DISMISSED** [review]

**Comment by mihrab34** [comment]
@manancodes. there's a failing check, which has to do with permission. Can you review the branch or token permission?

actionfail

**Review by manancodes — APPROVED** [review]

**Pull request closed without merging**
