### PR TITLE
removed the unused css styles

### LINKED ISSUE #29: Remove legacy code
Please go through the whole repo and try to find unused code or things which are not supposed to be there.

For example:
https://github.com/manancodes/Screenbows/blob/911857b58d44f06686e0dc670bd9afd815db6fa4/src/Components/Console/index.js#L31-L36

The `Shuffle` word is not being used but the icon, so It can be removed.

### PR DESCRIPTION
**Pull request by joanita-51**
In this pull request, I've addressed the feedback from issue #29 by removing the unused styles.button class from the <button> tag and the styles.input class from the <input> tag. These styles were not in use.

Closes : #29

### CODE REVIEW

**Comment by manancodes** [comment]
Please remove the unused CSS as well.

**Comment by joanita-51** [comment]
> Please remove the unused CSS as well.

Alright @manancodes. It also looks like the CSS in App.module.css isn't being utilized anywhere. Should i consider removing the file?

**Comment by manancodes** [comment]
Yes please. 

And thanks for the contribution. I'll be merging this once you do that.

**Comment by joanita-51** [comment]
> Yes please.
> 
> And thanks for the contribution. I'll be merging this once you do that.

Alright

**Review by manancodes — APPROVED** [review]

**Comment by manancodes** [comment]
Awesome work @joanita-51. Merging this now

**Pull request merged**
