### PR TITLE
Added, change colour when spacebar is pressed feature.

### LINKED ISSUE #25: Generate random colour when Space bar is pressed
Add a feature to generate a random colour when the spacebar is pressed. Just like it is used on https://coolors.co/

### PR DESCRIPTION
**Pull request by AbhimanyuAjudiya**
Fixed #25

### CODE REVIEW

**Review by manancodes — COMMENTED** [review]
Will `getRandomColors()` be called on the initial render? Have you tested this properly?

**Comment by AbhimanyuAjudiya** [comment]
> Will `getRandomColors()` be called on the initial render? Have you tested this properly?

yes it will works properly, I have tested it properly.

**Comment by manancodes** [comment]
> > Will `getRandomColors()` be called on the initial render? Have you tested this properly?
> 
> yes it will works properly, I have tested it properly.

Can you explain how the function will be called initially if spacebar is not pressed?

**Comment by AbhimanyuAjudiya** [comment]
initially useEffect() will called once due to second parameter '[]' and it will return a call back function where we have specified the `getRandomColors()` and in useEffect() we use return to clean up any side effects that we might have created.

**Review by manancodes — APPROVED** [review]

**Comment by manancodes** [comment]
Thanks for your contribution. Please check out other issues as well. Happy coding..

**Pull request merged**
