### PR TITLE
Update App.js

### PR DESCRIPTION
**Pull request by Emmarie-Ahtunan**
Adding gradient feature to app.js

### CODE REVIEW

**Comment by manancodes** [comment]
Please add all the changes in a single PR. Also, there is some issue with the compilation, can you please check your code again?

**Comment by manancodes** [comment]
I think you are using ChatGPT or some AI to solve this, which is fine, but you need to implement properly. I can see tons of problems in the current implementation.

**Comment by Emmarie-Ahtunan** [comment]
I'm actually not using AI to solve this; I just added a similar gradient function to a project I was working on but I'll look again. Thanks.

**Comment by manancodes** [comment]
No worries. Goodluck. Let me know if you need help.

**Pull request closed without merging**
