### PR TITLE
feat: Add Automated Deployment

### PR DESCRIPTION
**Pull request by mihrab34**
**closes** #24 

I have added a workflow that runs when a push is made to the master branch and it gets uploaded to gh-pages automatically

### CODE REVIEW

**Comment by manancodes** [comment]
LGTM

**Review by manancodes — APPROVED** [review]

**Comment by manancodes** [comment]
@mihrab34 , The workflow is failing, can you check this again.
Screenshot 2023-10-23 at 8 37 24 PM

**Comment by mihrab34** [comment]
@manancodes  Okay, I'll check it out. Can i get details on the workflow run that failed and the error message?

**Comment by manancodes** [comment]
> @manancodes Okay, I'll check it out. Can i get details on the workflow run that failed and the error message?

I've attached a screenshot in my above comment.

**Pull request merged**
