### PR TITLE
Application title

### PR DESCRIPTION
**Pull request by joanita-51**
I updated the application title as described in issue #39 
Title image

### CODE REVIEW

**Comment by manancodes** [comment]
I don't understand why this has the issue template changes as well?

**Comment by manancodes** [comment]
Also please check my comment https://github.com/manancodes/Screenbows/issues/39#issuecomment-1782514332

**Comment by joanita-51** [comment]
> I don't understand why this has the issue template changes as well?

It is because the pull request was created before the changes to the master branch, which included updates to the issue template

**Comment by joanita-51** [comment]
> Also please check my comment [#39 (comment)](https://github.com/manancodes/Screenbows/issues/39#issuecomment-1782514332)

Alright

**Comment by manancodes** [comment]
> > I don't understand why this has the issue template changes as well?
> 
> It is because the pull request was created before the changes to the master branch, which included updates to the issue template

That's what I'm confused about. The changes have already been made to the master, when why are we seeing this those additions now?

**Comment by joanita-51** [comment]
> > > I don't understand why this has the issue template changes as well?
> > 
> > 
> > It is because the pull request was created before the changes to the master branch, which included updates to the issue template
> 
> That's what I'm confused about. The changes have already been made to the master, when why are we seeing this those additions now?

The problem was in the time difference since the additions were made yesterday, and the merge was just completed. I believe the merge has resolved any issues, and it should be fine now.

**Comment by joanita-51** [comment]
> > Also please check my comment [#39 (comment)](https://github.com/manancodes/Screenbows/issues/39#issuecomment-1782514332)
> 
> Alright

This is the favicon image that has been added:
favicon image

And here's how it appears on the screen in the title:
title favicon

@manancodes , let me know if everything looks good now

**Comment by manancodes** [comment]
Can you please use this? Use a background remover tool to remove the background and just use the S. Make sure it does not stretch. The one you used looks a bit outdated.

https://labs.openai.com/s/OvhQnBY1Yp8aieP8S9pP6Km7

**Comment by joanita-51** [comment]
> Can you please use this? Use a background remover tool to remove the background and just use the S. Make sure it does not stretch. The one you used looks a bit outdated.
> 
> https://labs.openai.com/s/OvhQnBY1Yp8aieP8S9pP6Km7

Alright, is this new included favicon okay now? 
new favicon

**Comment by manancodes** [comment]
LGTM

**Pull request merged**
